"""I fucked up, change the location of the xp_multiplier column

Revision ID: 15cf8a1f773f
Revises: 408feca0924a
Create Date: 2025-07-06 01:11:52.957862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cf8a1f773f'
down_revision: Union[str, None] = '408feca0924a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'multiplier')
    op.add_column('logs', sa.Column('xp_multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'xp_multiplier')
    op.add_column('levels', sa.Column('multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
