"""remove overage column from Registration table

Revision ID: 31f6973674bb
Revises: b2a83bd47a96
Create Date: 2025-03-25 20:19:56.545715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f6973674bb'
down_revision: Union[str, None] = 'b2a83bd47a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'overage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('overage', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
