"""add nsfw column to Registration table

Revision ID: 3bc922095042
Revises: 31f6973674bb
Create Date: 2025-03-25 20:29:18.716291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc922095042'
down_revision: Union[str, None] = '31f6973674bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('nsfw', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'nsfw')
    # ### end Alembic commands ###
