"""Remove foreign key from levels table

Revision ID: 408feca0924a
Revises: bf336b43c2c5
Create Date: 2025-07-06 01:06:34.572913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408feca0924a'
down_revision: Union[str, None] = 'bf336b43c2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('levels_user_id_fkey', 'levels', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('levels_user_id_fkey', 'levels', 'registrations', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
