"""Add reaction logging column

Revision ID: 5e5bfedce330
Revises: d21c5d60de2d
Create Date: 2025-03-13 00:07:45.096322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5bfedce330'
down_revision: Union[str, None] = 'd21c5d60de2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('reaction_logging', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'reaction_logging')
    # ### end Alembic commands ###
