"""Remove level field from levels table, ill calculate it manually each time

Revision ID: 84ac45799fba
Revises: 15cf8a1f773f
Create Date: 2025-07-06 01:51:47.322861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ac45799fba'
down_revision: Union[str, None] = '15cf8a1f773f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
