"""add lockout columns to Registration table

Revision ID: b2a83bd47a96
Revises: 5e5bfedce330
Create Date: 2025-03-25 19:58:22.554008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a83bd47a96'
down_revision: Union[str, None] = '5e5bfedce330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('nsfw_lockout', sa.Boolean(), nullable=True))
    op.add_column('registrations', sa.Column('artist_lockout', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'artist_lockout')
    op.drop_column('registrations', 'nsfw_lockout')
    # ### end Alembic commands ###
