"""Add new multiplier column to Levels table

Revision ID: bf336b43c2c5
Revises: b2776e19bfa4
Create Date: 2025-07-06 01:03:41.248322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf336b43c2c5'
down_revision: Union[str, None] = 'b2776e19bfa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'multiplier')
    # ### end Alembic commands ###
