"""changes to Levels table

Revision ID: d1e61d9c1ca6
Revises: 1f01f74f4bfb
Create Date: 2025-03-27 01:15:34.058413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e61d9c1ca6'
down_revision: Union[str, None] = '1f01f74f4bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('levels', 'xp',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index('ix_guild', 'levels', ['guild_id'], unique=False)
    op.drop_constraint('levels_user_id_fkey', 'levels', type_='foreignkey')
    op.create_foreign_key(None, 'levels', 'registrations', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'levels', type_='foreignkey')
    op.create_foreign_key('levels_user_id_fkey', 'levels', 'registrations', ['user_id'], ['user_id'])
    op.drop_index('ix_guild', table_name='levels')
    op.alter_column('levels', 'xp',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('levels', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
