"""Add registration and levels stuff

Revision ID: d21c5d60de2d
Revises: 9c1bde6980ec
Create Date: 2025-02-27 23:50:37.448576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21c5d60de2d'
down_revision: Union[str, None] = '9c1bde6980ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('overage', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('sexuality', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('dms', sa.String(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('mention', sa.Boolean(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('registered_at', sa.BigInteger(), nullable=True),
    sa.Column('age_verified', sa.Boolean(), nullable=True),
    sa.Column('artist_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('levels',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['logs.guild_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['registrations.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'guild_id')
    )
    op.create_index('ix_user_guild', 'levels', ['user_id', 'guild_id'], unique=False)
    op.alter_column('custom_commands', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'logs', ['guild_id'])
    op.alter_column('punishments', 'guild_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('punishments', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('punishments', 'punishment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('punishments', 'punishment_time',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('punishments', 'moderator_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('punishments', 'moderator_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('punishments', 'punishment_time',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('punishments', 'punishment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('punishments', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('punishments', 'guild_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'logs', type_='unique')
    op.alter_column('custom_commands', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('ix_user_guild', table_name='levels')
    op.drop_table('levels')
    op.drop_table('registrations')
    # ### end Alembic commands ###
